package com.jcsla.korailsrt.presentation.entity.dto.request

import com.jcsla.korailsrt.presentation.entity.dto.response.Train

data class TicketReservationRequest(
    override var Device: String = "AD",
    override var Version: String = "190617001",
    override var Key: String = "korail01234567890",
    val txtGdNo: String = "",
    val txtJobId: String = "1101",
    val txtTotPsgCnt: String,
    val txtSeatAttCd1: String = "000",
    val txtSeatAttCd2: String = "000",
    val txtSeatAttCd3: String = "000",
    val txtSeatAttCd4: String = "015",
    val txtSeatAttCd5: String = "000",
    val hidFreeFlg: String = "N",
    val txtStndFlg: String = "N",
    val txtMenuId: String = "11",
    val txtSrcarCnt: String = "0",
    val txtJrnyCnt: String = "1",
    val txtJrnySqno1: String = "001",
    val txtJrnyTpCd1: String = "11",
    val txtDptDt1: String,
    val txtDptRsStnCd1: String,
    val txtDptTm1: String,
    val txtArvRsStnCd1: String,
    val txtTrnNo1: String,
    val txtRunDt1: String,
    val txtTrnClsfCd1: String,
    val txtPsrmClCd1: String,
    val txtTrnGpCd1: String,
    val txtChgFlg1: String = "",
    val txtJrnySqno2: String = "",
    val txtJrnyTpCd2: String = "",
    val txtDptDt2: String = "",
    val txtDptRsStnCd2: String = "",
    val txtDptTm2: String = "",
    val txtArvRsStnCd2: String = "",
    val txtTrnNo2: String = "",
    val txtRunDt2: String = "",
    val txtTrnClsfCd2: String = "",
    val txtPsrmClCd2: String = "",
    val txtChgFlg2: String = "",
    val txtPsgTpCd1: String = "1",
    val txtDiscKndCd1: String = "000",
    val txtCompaCnt1: String,
    val txtCardCode_1: String = "",
    val txtCardNo_1: String = "",
    val txtCardPw_1: String = ""
) : Request {

    constructor(train: Train) : this(
        txtTotPsgCnt = "1",
        txtDptDt1 = train.h_dpt_dt,
        txtDptRsStnCd1 = train.h_dpt_rs_stn_cd,
        txtDptTm1 = train.h_dpt_tm,
        txtArvRsStnCd1 = train.h_arv_rs_stn_cd,
        txtTrnNo1 = train.h_trn_no,
        txtRunDt1 = train.h_run_dt,
        txtTrnClsfCd1 = train.h_trn_clsf_cd,
        txtPsrmClCd1 = "1",
        txtTrnGpCd1 = train.h_trn_gp_cd,
        txtCompaCnt1 = "1"
    )

    override fun getRequestBody(): Map<String, String> {
        return mapOf(
            ::Key.name to Key,
            ::Device.name to Device,
            ::Version.name to Version,
            ::txtGdNo.name to txtGdNo,
            ::txtJobId.name to txtJobId,
            ::txtTotPsgCnt.name to txtTotPsgCnt,
            ::txtSeatAttCd1.name to txtSeatAttCd1,
            ::txtSeatAttCd2.name to txtSeatAttCd2,
            ::txtSeatAttCd3.name to txtSeatAttCd3,
            ::txtSeatAttCd4.name to txtSeatAttCd4,
            ::txtSeatAttCd5.name to txtSeatAttCd5,
            ::hidFreeFlg.name to hidFreeFlg,
            ::txtStndFlg.name to txtStndFlg,
            ::txtMenuId.name to txtMenuId,
            ::txtSrcarCnt.name to txtSrcarCnt,
            ::txtJrnyCnt.name to txtJrnyCnt,
            ::txtJrnySqno1.name to txtJrnySqno1,
            ::txtJrnyTpCd1.name to txtJrnyTpCd1,
            ::txtDptDt1.name to txtDptDt1,
            ::txtDptRsStnCd1.name to txtDptRsStnCd1,
            ::txtDptTm1.name to txtDptTm1,
            ::txtArvRsStnCd1.name to txtArvRsStnCd1,
            ::txtTrnNo1.name to txtTrnNo1,
            ::txtRunDt1.name to txtRunDt1,
            ::txtTrnClsfCd1.name to txtTrnClsfCd1,
            ::txtPsrmClCd1.name to txtPsrmClCd1,
            ::txtTrnGpCd1.name to txtTrnGpCd1,
            ::txtChgFlg1.name to txtChgFlg1,
            ::txtJrnySqno2.name to txtJrnySqno2,
            ::txtJrnyTpCd2.name to txtJrnyTpCd2,
            ::txtDptDt2.name to txtDptDt2,
            ::txtDptRsStnCd2.name to txtDptRsStnCd2,
            ::txtDptTm2.name to txtDptTm2,
            ::txtArvRsStnCd2.name to txtArvRsStnCd2,
            ::txtTrnNo2.name to txtTrnNo2,
            ::txtRunDt2.name to txtRunDt2,
            ::txtTrnClsfCd2.name to txtTrnClsfCd2,
            ::txtPsrmClCd2.name to txtPsrmClCd2,
            ::txtChgFlg2.name to txtChgFlg2,
            ::txtPsgTpCd1.name to txtPsgTpCd1,
            ::txtDiscKndCd1.name to txtDiscKndCd1,
            ::txtCompaCnt1.name to txtCompaCnt1,
            ::txtCardCode_1.name to txtCardCode_1,
            ::txtCardNo_1.name to txtCardNo_1,
            ::txtCardPw_1.name to txtCardPw_1
        )
    }
}