package com.jcsla.korailsrt.presentation.entity.dto.response

data class ScheduleViewResponse(
    override val h_msg_cd: String,
    override val h_msg_txt: String,
    override val strResult: String,
    val strJobId: String,
    val h_menu_id: String,
    val h_gd_no: String,
    val h_seat_cnt_first: String,
    val h_seat_cnt_second: String,
    val h_next_pg_flg: String,
    val txtGoHour_first: String,
    val h_rslt_cnt: String,
    val h_agree_txt: String,
    val trn_infos: TrainInfos,
    val h_notice_msg: String
) : Response(h_msg_cd, strResult, h_msg_txt)

data class TrainInfos(
    val trn_info: List<Train>
)

data class Train(
    val h_trn_seq: String,
    val h_chg_trn_dv_cd: String,
    val h_chg_trn_dv_nm: String,
    val h_chg_trn_seq: String,
    val h_dpt_rs_stn_cd: String,
    val h_dpt_rs_stn_nm: String,
    val h_arv_rs_stn_cd: String,
    val h_arv_rs_stn_nm: String,
    val h_trn_no: String,
    val h_trn_no_qb: String,
    val h_yms_apl_flg: String,
    val h_trn_gp_cd: String,
    val h_trn_clsf_cd: String,
    val h_run_dt: String,
    val h_dpt_dt: String,
    val h_dpt_tm: String,
    val h_dpt_tm_qb: String,
    val h_arv_dt: String,
    val h_arv_tm: String,
    val h_arv_tm_qb: String,
    val h_expct_dlay_hr: String,
    val h_rsv_wait_ps_cnt: String,
    val h_dtour_flg: String,
    val h_dtour_txt: String,
    val h_std_rest_seat_cnt: String,
    val h_fst_rest_seat_cnt: String,
    val h_car_tp_cd: String,
    val h_car_tp_nm: String,
    val h_trn_cps_cd1: String,
    val h_trn_cps_nm1: String,
    val h_trn_cps_cd2: String,
    val h_trn_cps_nm2: String,
    val h_trn_cps_cd3: String,
    val h_trn_cps_nm3: String,
    val h_trn_cps_cd4: String,
    val h_trn_cps_nm4: String,
    val h_trn_cps_cd5: String,
    val h_trn_cps_nm5: String,
    val h_train_disc_rt: String,
    val h_wait_rsv_flg: String,
    val h_rd_cnd_disc_no: String,
    val h_rd_cnd_disc_nm: String,
    val h_spe_rsv_cd: String,
    val h_spe_rsv_cd2: String,
    val h_spe_rsv_nm: String,
    val h_spe_disc_rt: String,
    val h_spe_seat_map_flg: String,
    val h_gen_rsv_cd: String,
    val h_gen_rsv_cd2: String,
    val h_gen_rsv_nm: String,
    val h_gen_disc_rt: String,
    val h_gen_seat_map_flg: String,
    val h_stnd_rsv_cd: String,
    val h_stnd_rsv_nm: String,
    val h_free_rsv_cd: String,
    val h_free_rsv_nm: String,
    val h_free_sracar_cnt: String,
    val h_train_disc_gen_rt: String,
    val h_rd_add_info: String,
    val h_nonstop_msg: String,
    val h_nonstop_msg_txt: String,
    val h_rd_seat_map_flg: String,
    val h_dpt_stn_cons_ordr: String,
    val h_arv_stn_cons_ordr: String,
    val h_dpt_stn_run_ordr: String,
    val h_arv_stn_run_ordr: String,
    val h_seat_att_cd: String,
    val h_rcvd_amt: String,
    val h_rcvd_fare: String,
    val h_cnec_trfc_psb_flg: String,
    val h_cnec_trfc_nd_hm: String,
    val h_cnec_trfc_rcvd_prc: String,
    val h_rsv_psb_flg: String,
    val h_rsv_psb_nm: String,
    val h_stn_sale_flg: String,
    val h_stn_sale_txt: String,
    val h_info_txt: String,
    val h_trn_clsf_nm: String,
    val h_trn_gp_nm: String
)